version: '2'

run:
  modules-download-mode: readonly
  issues-exit-code: 1

linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - copyloopvar
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - predeclared
    - revive
    - staticcheck
    - thelper
    - tparallel
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    errcheck:
      check-blank: true
    exhaustive:
      check:
        - switch
    gocritic:
      disabled-checks:
        - hugeParam
        - rangeExprCopy
        - rangeValCopy
      enabled-tags:
        - diagnostic
        - performance
        - style
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - inline
    nakedret:
      max-func-lines: 1
    revive:
      rules:
        - name: var-naming
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: '(.+)_test\.go'

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      simplify: true
